/**
 * Deck B: the back half of the night.
 *
 * Deck A opens the evening, so this half is the bill arriving. Nothing here is a
 * problem you walked up to fresh: the ledger has already been inked, the body
 * has already been in the pond a fortnight, the oath was already sworn in
 * spring, and somebody has already picked the lock you were going to pick. The
 * generator can draw an Act from either pool, and the tonal escalation has to
 * survive being drawn at random, so it lives in the fiction rather than in the
 * ordering: cold, water, debt, corpses and the uncanny, all of it consequence
 * for something that happened off screen.
 *
 * Two shaping rules, both about keeping the choice live.
 *
 * The Reckless line pays most here because the safe lines are genuinely worse
 * than in Deck A. Target numbers sit higher across the board and the middle
 * option usually costs Dread, so flinching stops being cheap and the table has
 * to argue about who goes.
 *
 * And at least a third of these scenes offer a real way out of a violent
 * situation that is not violence: three barrels instead of a broken hand, the
 * offal barrel instead of the yard broom, the spring's labour instead of the
 * pewter. They are cheap, they are low target numbers, and they pay less than
 * going through the door. That gap is the whole decision. A player who takes the
 * quiet option every Act finishes the night alive, respected by nobody, and
 * short of the Hoard, which is the correct outcome and should feel like one.
 *
 * Tags come from lib/content/tags.ts and nowhere else. Numbers are tuned against
 * the Dread thresholds in rules.ts and are not repeated here.
 */
import type { Scene } from "@/lib/game/types";

export const SCENES_B: Scene[] = [
  {
    id: "b1",
    title: "The Ledger in the Yard",
    setup:
      "A woman with a ledger and two quiet men are standing where the barrels come in. She has been waiting since second bell and she has the landlord's mark already inked beside a number.",
    tags: ["debt", "drink"],
    approaches: [
      {
        id: "b1a",
        label: "Offer her three barrels and the winter's carting",
        ability: "charm",
        tn: 11,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "She licks the pencil, writes in the margin, and takes the barrels instead of a finger.",
        lose: "She writes nothing, which is how everyone in the yard learns what you are worth.",
      },
      {
        id: "b1b",
        label: "Hold the yard gate while the till goes out the front",
        ability: "brawn",
        tn: 13,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "The gate holds, the till leaves under an apron, and nobody in the yard can prove a thing.",
        lose: "The gate comes off its hinges with you still holding on to it.",
      },
      {
        id: "b1r",
        label: "Lift the ledger out of her hands and put it in the hearth",
        ability: "deft",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "The pages go up green and sweet, and for one winter nobody in this village owes anybody anything.",
        lose: "She has hold of the wrist you reached with, and she is in no hurry to let go of it.",
      },
    ],
  },
  {
    id: "b2",
    title: "What the Pond Kept",
    setup:
      "There is a hand up through the mill pond ice, palm open, and the miller says it has been there since the frost came. Nobody has wanted to be the one to look at the rest of him.",
    tags: ["cold", "corpse", "water"],
    approaches: [
      {
        id: "b2a",
        label: "Read the ice and lift him out with the hay hook",
        ability: "wits",
        tn: 12,
        deed: 4,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "The ice takes your weight exactly where you said it would, and he comes up in one piece.",
        lose: "The hook finds him, the ice finds you, and the miller has to pull on your belt.",
      },
      {
        id: "b2b",
        label: "Wade the shallow end and break a path with your boots",
        ability: "grit",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You get him to the bank on legs you cannot feel, and somebody puts a coat over both of you.",
        lose: "The cold gets into you faster than you get to him, and you come back with nothing.",
      },
      {
        id: "b2r",
        label: "Go under at the sluice and bring him up whole",
        ability: "nerve",
        tn: 18,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You come up through the hole with him held against you, and the whole yard stops talking.",
        lose: "You find him in the dark under the ice, and then you have to find the hole again.",
      },
    ],
  },
  {
    id: "b3",
    title: "The Promise, Collected",
    setup:
      "The woman in grey has come with a candle and the exact words you used in the spring. She is not angry, she is simply here, and the room is quiet enough to hear the wax.",
    tags: ["oath", "clergy"],
    approaches: [
      {
        id: "b3a",
        label: "Argue the wording down to something smaller",
        ability: "charm",
        tn: 10,
        deed: 4,
        cost: { renown: 1, dread: 0 },
        reckless: false,
        win: "She allows that the spring was a long time ago, and names a lighter version of it.",
        lose: "She repeats your words back to you until you stop talking, and the room hears every one.",
      },
      {
        id: "b3b",
        label: "Kneel, keep it, and pay the penance in front of them",
        ability: "grit",
        tn: 12,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You keep the promise on the flags in front of witnesses, and the candle is put out gently.",
        lose: "You get halfway through the penance and your knees decide the rest of it for you.",
      },
      {
        id: "b3r",
        label: "Say no, out loud, with the candle still lit",
        ability: "nerve",
        tn: 16,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "She looks at you for a long moment, pinches the flame out herself, and leaves the words with you.",
        lose: "The candle stays lit, and now everyone in the room knows what your word is good for.",
      },
    ],
  },
  {
    id: "b4",
    title: "The Watch on the Low Bridge",
    setup:
      "Two of the watch have an end of the bridge each and a lantern between them, and one of them is reading out a description that fits you closely enough. The river is loud under the boards.",
    tags: ["patrol", "height", "water"],
    approaches: [
      {
        id: "b4a",
        label: "Give them a name, a trade and a reason to be bored",
        ability: "charm",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "They lose interest somewhere in the middle of your carting business and wave you through.",
        lose: "The one with the paper asks you to say the name again, slower, and writes it down.",
      },
      {
        id: "b4b",
        label: "Go over the rail and along the ledge under the boards",
        ability: "deft",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You come up on the far bank with wet hands and the lantern still where it was.",
        lose: "The ledge is narrower than it looked and the lantern comes to the rail to find out why.",
      },
      {
        id: "b4r",
        label: "Take the drop and let the river carry you past them",
        ability: "grit",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "The river puts you out below the weir, coughing, half a mile from anyone who wanted a word.",
        lose: "The river takes you where it likes, and you crawl out somewhere you did not choose.",
      },
    ],
  },
  {
    id: "b5",
    title: "The Cellar Is Filling",
    setup:
      "The cellar steps are under water to the fourth tread, and something is turning slowly in the dark by the far wall. The pump handle is down there too.",
    tags: ["water", "dark", "uncanny"],
    approaches: [
      {
        id: "b5a",
        label: "Work out where the water is coming in and stop it",
        ability: "wits",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "You find the broken conduit behind the barrels and pack it with sacking until it holds.",
        lose: "You are still working out the fall of the floor when the water reaches the third tread.",
      },
      {
        id: "b5b",
        label: "Get the pump going and keep going after your arms stop",
        ability: "brawn",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "The water goes down a tread, then another, and whatever was turning is not there any more.",
        lose: "The pump gives out before you do, and you stand in the dark listening to it come back up.",
      },
      {
        id: "b5r",
        label: "Take a light down and see what is turning",
        ability: "nerve",
        tn: 17,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You go down, you look at it properly, and you come back up able to say what it was.",
        lose: "The light goes out before you reach the far wall, and the turning does not stop.",
      },
    ],
  },
  {
    id: "b6",
    title: "The Shambles Dogs",
    setup:
      "Six dogs have the butcher's yard, and one of them has something that used to be wearing a boot. They have stopped barking, which is the part the butcher does not like.",
    tags: ["beast", "corpse"],
    approaches: [
      {
        id: "b6a",
        label: "Empty the offal barrel at the far gate and let them choose",
        ability: "wits",
        tn: 11,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "They choose the barrel, because they were always going to choose the barrel.",
        lose: "Four go to the barrel and two stay exactly where they are, watching you.",
      },
      {
        id: "b6b",
        label: "Stand in the gap with the yard broom and give no ground",
        ability: "nerve",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You hold the gap long enough for the butcher to get the hurdles across, and nothing gets past you.",
        lose: "The big one comes low and under the broom, and the gap is not held after that.",
      },
      {
        id: "b6r",
        label: "Go in and take the boot back off the big one",
        ability: "brawn",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You come out of the yard with the boot, and there is enough of the man left inside it to bury.",
        lose: "You get a hand on the boot, and then the yard is all teeth and you are on the cobbles.",
      },
    ],
  },
  {
    id: "b7",
    title: "After the Granary",
    setup:
      "The granary burned at dusk and everything that lived in its floor is now in the lane. The grain that survived is in sacks that nobody wants to carry through that.",
    tags: ["vermin", "fire", "ruins"],
    approaches: [
      {
        id: "b7a",
        label: "Walk the sacks out through them, one at a time, quickly",
        ability: "grit",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You make eleven trips, you do not look down, and the village eats in the spring.",
        lose: "Something goes up your sleeve on the sixth trip and the sack ends up in the gutter.",
      },
      {
        id: "b7b",
        label: "Smoke the lane and drive them the other way",
        ability: "wits",
        tn: 13,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "The lane clears in one long grey wave towards the water, and the sacks come out clean.",
        lose: "The wind turns at the wrong moment and drives the whole lane back over your boots.",
      },
      {
        id: "b7r",
        label: "Go up into the loft where the heat still is for the seed corn",
        ability: "deft",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You come down the outside of the wall with next year's seed corn on your back.",
        lose: "The loft floor is not a floor any more, and you find that out with one foot.",
      },
    ],
  },
  {
    id: "b8",
    title: "The Upper Room Is Alight",
    setup:
      "The thatch on the end house has gone and there is somebody at the upper window who has stopped shouting. The lane is holding a ladder that is two rungs short.",
    tags: ["fire", "height", "crowd"],
    approaches: [
      {
        id: "b8a",
        label: "Get the lane organised into a chain of buckets",
        ability: "charm",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "Thirty people who were watching become a line to the trough, and the end wall is saved.",
        lose: "Everyone agrees with you, nobody moves, and the fire uses the time you gave it.",
      },
      {
        id: "b8b",
        label: "Take the ladder up and hold the sill with one hand",
        ability: "deft",
        tn: 14,
        deed: 6,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You get an arm through the window and the lane takes the weight of both of you.",
        lose: "The sill is hotter than you allowed for and the ladder is still two rungs short.",
      },
      {
        id: "b8r",
        label: "Go in at the door and up through it",
        ability: "grit",
        tn: 18,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You come out of the doorway carrying somebody, and the roof comes down behind you.",
        lose: "The stairs are gone by the second turn, and you come back out with your eyebrows and nothing else.",
      },
    ],
  },
  {
    id: "b9",
    title: "The Season's Due",
    setup:
      "The lord's man has the door open and a list in his hand, and he has already counted the pewter. He is polite, and he has four riders in the lane being polite as well.",
    tags: ["gentry", "debt", "trade"],
    approaches: [
      {
        id: "b9a",
        label: "Offer him the spring's labour instead of the pewter",
        ability: "charm",
        tn: 11,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "He writes down four weeks of your spring and puts the pewter back on the shelf.",
        lose: "He hears you out, thanks you for it, and takes the pewter anyway.",
      },
      {
        id: "b9b",
        label: "Find the error on his list and make him read it aloud",
        ability: "wits",
        tn: 14,
        deed: 6,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "He reads the same line twice, goes the colour of the pewter, and shortens the list himself.",
        lose: "There is no error, or none you can point at, and now he is reading the list slowly.",
      },
      {
        id: "b9r",
        label: "Put the list in the fire and the man in the lane",
        ability: "brawn",
        tn: 17,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "The list burns, the riders take him home, and this house is not on next season's paper.",
        lose: "The list survives, and so does his memory of exactly whose house this is.",
      },
    ],
  },
  {
    id: "b10",
    title: "The Wake Turns",
    setup:
      "The dead man's brothers have stopped drinking to his memory and started drinking at each other. He is still on the table, and somebody has already moved the knives, which means somebody thought about it.",
    tags: ["drink", "crowd", "corpse"],
    approaches: [
      {
        id: "b10a",
        label: "Get up on the bench and give him the send off nobody else will",
        ability: "charm",
        tn: 12,
        deed: 5,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "By the third verse both brothers are crying instead of squaring up, which is what a wake is for.",
        lose: "You get four words in before somebody tells you what he was really like, and the room agrees.",
      },
      {
        id: "b10b",
        label: "Get between the brothers and stay there",
        ability: "grit",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You take everything either of them meant for the other, and the wake goes on around you.",
        lose: "You are between them for about as long as it takes them to agree about you.",
      },
      {
        id: "b10r",
        label: "Take the table out from under him and empty the room",
        ability: "brawn",
        tn: 16,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "The table goes over, the room goes out into the lane, and he is left in peace at last.",
        lose: "The table goes over, and he is on the floor, and the room has stopped caring who started it.",
      },
    ],
  },
  {
    id: "b11",
    title: "The Well in the Old Almshouse",
    setup:
      "The almshouse has no roof and the well in the middle of it is dry, and something down there is answering in your own voice, half a breath late. Somebody's coat is folded neatly on the wall.",
    tags: ["uncanny", "ruins", "dark"],
    approaches: [
      {
        id: "b11a",
        label: "Work out what this room was for before you answer it",
        ability: "wits",
        tn: 13,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You find the drain, the slope and the sealed door, and after that the voice is only a voice.",
        lose: "You are still reading the walls when it starts saying things you have not said yet.",
      },
      {
        id: "b11b",
        label: "Say nothing at all, and go down the rope for the coat",
        ability: "deft",
        tn: 15,
        deed: 6,
        cost: { renown: 3, dread: 1 },
        reckless: false,
        win: "You come up with the coat and its pockets, and you have not given it one word.",
        lose: "The rope holds and your mouth does not, and it has something of yours now.",
      },
      {
        id: "b11r",
        label: "Answer it until it runs out of your words",
        ability: "nerve",
        tn: 18,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "It runs dry before you do, and the almshouse is just a wall and a hole in the ground.",
        lose: "It does not run out, and by the end you are the one repeating.",
      },
    ],
  },
  {
    id: "b12",
    title: "Somebody Got to the Strongroom First",
    setup:
      "The strongroom door stands open a hand's width and there is a light moving inside it that is not yours. Whoever they are, they have already done the difficult part of the lock.",
    tags: ["thief", "lock"],
    approaches: [
      {
        id: "b12a",
        label: "Knock, walk in, and offer to carry half",
        ability: "charm",
        tn: 12,
        deed: 5,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "Two of you carry twice as much twice as fast, and neither of you has to explain the noise.",
        lose: "They take the offer, then take the stairs, then take the lot.",
      },
      {
        id: "b12b",
        label: "Wait in the dark, then take what they leave behind",
        ability: "nerve",
        tn: 13,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "They go out heavy and careless, and what they were too greedy to sort through is still there.",
        lose: "They are thorough, they are slow, and the house is awake before they are finished.",
      },
      {
        id: "b12r",
        label: "Take the door, the light and the bag off them",
        ability: "deft",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You come out with all of it and they come out with a story nobody will believe.",
        lose: "The bag tears between you, the light goes over, and the shouting starts upstairs.",
      },
    ],
  },
  {
    id: "b13",
    title: "The Shepherd on the Moor Road",
    setup:
      "The shepherd is sitting against the wall with his crook across his knees and frost in his beard, and he has been sitting there a while. There are shapes on the ridge that have been patient about it.",
    tags: ["cold", "corpse", "beast"],
    approaches: [
      {
        id: "b13a",
        label: "Build the fire high enough that patience stops paying",
        ability: "wits",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "The fire takes on the wet gorse, the ridge empties, and you sit with him until light.",
        lose: "You get smoke and no flame, and the shapes come a little further down to watch.",
      },
      {
        id: "b13b",
        label: "Carry him down and worry about the ridge later",
        ability: "grit",
        tn: 13,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You get him to the first wall of the village, and his own dog comes out to meet him.",
        lose: "He is heavier than a man should be and the road is longer than you remembered.",
      },
      {
        id: "b13r",
        label: "Walk up the ridge and stand there until they go",
        ability: "nerve",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You stand on the ridge with nothing in your hands and they decide the night is not worth it.",
        lose: "They do not go, and the walk back down is the longest thing you have ever done.",
      },
    ],
  },
  {
    id: "b14",
    title: "The Rope in the Bell Tower",
    setup:
      "The bell has to be rung to bring the village out, and the rope has three good feet of fraying at head height. The ladder up to the beam is older than the rope.",
    tags: ["height", "clergy", "ruins"],
    approaches: [
      {
        id: "b14a",
        label: "Splice it with what is in your pack and ring it properly",
        ability: "deft",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "The splice takes, the bell speaks the way it is supposed to, and doors open all down the street.",
        lose: "The splice slips on the second pull and the rope comes down around your shoulders.",
      },
      {
        id: "b14b",
        label: "Hang your whole weight on the bad part and keep pulling",
        ability: "brawn",
        tn: 15,
        deed: 6,
        cost: { renown: 3, dread: 1 },
        reckless: false,
        win: "You get nine strokes out of a rope that had no business giving you three.",
        lose: "It parts at the fourth stroke and puts you on the flags with the bell still swinging.",
      },
      {
        id: "b14r",
        label: "Go up the ladder to the beam and strike the bell by hand",
        ability: "grit",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You sit on the beam and beat the bell with the flat of your hand until the whole valley is up.",
        lose: "The ladder gives at the third rung from the top, and the tower is a long thing to fall inside.",
      },
    ],
  },
  {
    id: "b15",
    title: "The Toll on the Ash Road",
    setup:
      "There is a man at the boundary stone who is owed something by everybody who has come this way tonight, and he asks for it by name. He has your name, and the wind has dropped.",
    tags: ["oath", "trade", "uncanny"],
    approaches: [
      {
        id: "b15a",
        label: "Give him something of yours worth more than the toll",
        ability: "charm",
        tn: 12,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "He weighs it, he is satisfied, and he steps off the road to let you by.",
        lose: "He turns it over twice, hands it back, and asks for your name again.",
      },
      {
        id: "b15b",
        label: "Work out what he is actually owed and pay exactly that",
        ability: "wits",
        tn: 14,
        deed: 6,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You pay the toll to the last part of it, and he cannot think of a reason to keep you.",
        lose: "You are short by something you did not know counted, and he is happy to wait.",
      },
      {
        id: "b15r",
        label: "Give him a false name and mean it",
        ability: "nerve",
        tn: 18,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "He writes down a name that is not yours, and whatever is owed is owed by somebody who does not exist.",
        lose: "He says the false name back to you, and then he says the real one.",
      },
    ],
  },
];
