/**
 * Deck A. The fifteen ordinary nights.
 *
 * These are the scenes the run is drawn from before Dread turns the night, so
 * every one of them has to be survivable by any party the draft happens to
 * produce. That is the constraint the whole set is shaped around, and it is why
 * each scene is three doors on three different abilities: the player who put the
 * high number in CHARM and the player who put it in BRAWN are both looking at a
 * door with their name on it, and neither of them is looking at the same one.
 *
 * The Reckless line is deliberately never the clever line. It pays most, it
 * asks most, and it costs most, and because its target number is hidden it is
 * the only place in the game where a player is guessing rather than solving. It
 * is one door, so taking it is also taking it away from somebody else.
 *
 * A third of these have nobody laying a hand on anybody. A cellar full of cold
 * water, a carter who will not sell, a table where the refusal arrives with the
 * fish. A party that drafted for talk and thinking has to be able to earn a
 * night, or half the character sheet is decoration.
 *
 * Tags are load-bearing rather than colour. A Hook guarantees its tag into the
 * deck and refills on it, so the spread here is the spread of nights the game
 * can promise: the cold ones, the high ones, the wet ones, the ones with the
 * watch in them, and the ones where the trouble is a price rather than a thing.
 */
import type { Scene } from "@/lib/game/types";
import type { Tag } from "@/lib/content/tags";

export const SCENES_A: Scene[] = [
  {
    id: "a01",
    title: "The Cellar Steps",
    setup:
      "The cellar has taken two feet of black water overnight and the landlord's strongbox is down there with the quarter's takings in it. The stairs go under at the fourth step.",
    tags: ["water", "cold", "dark"] satisfies Tag[],
    approaches: [
      {
        id: "a01-wade",
        label: "Wade the length of it",
        ability: "grit",
        tn: 11,
        deed: 3,
        cost: { renown: 1, dread: 0 },
        reckless: false,
        win: "You come back up shuddering with the box under one arm and your boots full of something you would rather not name.",
        lose: "The cold gets into your chest halfway along and you climb out with nothing but a story.",
      },
      {
        id: "a01-hook",
        label: "Fish it out with the beam hook",
        ability: "deft",
        tn: 13,
        deed: 4,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "The hook finds the handle on the third try and the box comes up slick, dripping and still shut.",
        lose: "The hook catches, slips, and the box goes over on its side somewhere under the black.",
      },
      {
        id: "a01-wall",
        label: "Break the far wall and let the cellar drain",
        ability: "brawn",
        tn: 16,
        deed: 7,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "The stones give and the water goes out into the yard in one long grey rush, and there sits the box in the mud.",
        lose: "The wall comes inwards rather than out, and you are under it in the dark with the level rising.",
      },
    ],
  },
  {
    id: "a02",
    title: "The Roof of the Wool Hall",
    setup:
      "The only way into the wool hall is over its roof, and the slates are wet with the afternoon's rain. Somebody else's ladder is already leaning against the north gable.",
    tags: ["height", "thief"] satisfies Tag[],
    approaches: [
      {
        id: "a02-ladder",
        label: "Go up the ladder first and fast",
        ability: "nerve",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "You are over the ridge and gone before the ladder has stopped shaking.",
        lose: "A slate goes out from under you and you come down into the gutter with your leg wrong.",
      },
      {
        id: "a02-hold",
        label: "Talk the other climber into holding it",
        ability: "charm",
        tn: 10,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "They hold the foot of it out of some professional courtesy that surprises you both.",
        lose: "They listen, they nod, and then they take the ladder with them.",
      },
      {
        id: "a02-jump",
        label: "Jump the gap to the chimney stack",
        ability: "deft",
        tn: 17,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You land badly and hold on anyway, and the whole hall is under you with nobody watching the roof.",
        lose: "The stack is older than it looks and it goes with you, brick by brick, into the yard.",
      },
    ],
  },
  {
    id: "a03",
    title: "A Price for the Grey Mare",
    setup:
      "The carter will not sell the grey mare and you need her by dusk. He has already turned down good coin twice this morning, in front of witnesses.",
    tags: ["trade", "beast", "gentry"] satisfies Tag[],
    approaches: [
      {
        id: "a03-figure",
        label: "Name a figure he cannot repeat to his neighbours",
        ability: "charm",
        tn: 13,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "He looks at his boots, spits, and hands you the halter without saying the number aloud.",
        lose: "He repeats your figure loudly, twice, and the whole row laughs at you.",
      },
      {
        id: "a03-foot",
        label: "Tell him what is wrong with her near hind",
        ability: "wits",
        tn: 11,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "You name the foot and he goes quiet, because he thought nobody had noticed.",
        lose: "You are wrong about the foot and he is glad to explain that, at length, to everybody.",
      },
      {
        id: "a03-road",
        label: "Stand in the road until he sells",
        ability: "grit",
        tn: 16,
        deed: 7,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You are still there at dusk and so is the mare, and it is the carter who gives in.",
        lose: "The cart goes round you through the ditch, and you spend the evening explaining yourself to the market clerk.",
      },
    ],
  },
  {
    id: "a04",
    title: "The Tithe Wagon",
    setup:
      "A temple wagon is stuck to its axles in the ford and the two novices guarding it want nobody near the crates. The tide in the estuary turns within the hour.",
    tags: ["clergy", "water"] satisfies Tag[],
    approaches: [
      {
        id: "a04-axle",
        label: "Get a shoulder under the axle",
        ability: "brawn",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "The wheel lifts out of the silt, the wagon rolls, and the novices are too grateful to search anybody.",
        lose: "Your back goes before the axle does, and the wagon settles deeper.",
      },
      {
        id: "a04-orders",
        label: "Give orders as though somebody sent you",
        ability: "charm",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "Three instructions in the right tone and the novices are carrying crates to wherever you point.",
        lose: "One of them asks who sent you, and you hear yourself answer.",
      },
      {
        id: "a04-traces",
        label: "Cut the traces and carry the crates across yourself",
        ability: "nerve",
        tn: 10,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "You come out on the far bank soaked to the waist with every crate dry and the tide behind you.",
        lose: "The water takes the wagon sideways and you go with it, holding a rope that is no longer attached to anything.",
      },
    ],
  },
  {
    id: "a05",
    title: "Hail on the Drove Road",
    setup:
      "Hail the size of teeth on an open road, and eighty sheep you were paid to bring in before dark. There is no shelter for a mile in any direction.",
    tags: ["cold", "beast"] satisfies Tag[],
    approaches: [
      {
        id: "a05-walk",
        label: "Keep walking and keep counting",
        ability: "grit",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "You come in long after dark with your hands ruined and the count right.",
        lose: "The tail of the flock goes somewhere in the white, and the count comes in short.",
      },
      {
        id: "a05-gate",
        label: "Turn the leaders by hand into the sunken lane",
        ability: "brawn",
        tn: 10,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "The lane is below the wind, and once the leaders are in the rest pour down after them like water.",
        lose: "You get in front of the leaders twice and both times they go round you, and the flock spreads.",
      },
      {
        id: "a05-ford",
        label: "Take them over the ford before it rises",
        ability: "wits",
        tn: 16,
        deed: 7,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "The last ewe comes out on the far bank and the water closes over the stones behind her.",
        lose: "The river takes four of them past you while you stand in it to your thighs, watching.",
      },
    ],
  },
  {
    id: "a06",
    title: "The Millrace Gate",
    setup:
      "The mill's sluice gate has jammed half open and the wheel is running fast enough to shake the building. The miller's boy is up on the walkway with an iron bar and no idea what to do with it.",
    tags: ["water", "height"] satisfies Tag[],
    approaches: [
      {
        id: "a06-rack",
        label: "Work the rack down by hand",
        ability: "brawn",
        tn: 13,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "The gate comes down a tooth at a time until the shaking stops, and the boy just stares at you.",
        lose: "The pinion strips and the bar comes back across the walkway at you.",
      },
      {
        id: "a06-jam",
        label: "Jam the wheel with the spare axle tree",
        ability: "deft",
        tn: 11,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "The timber goes in where the spokes are thinnest and the wheel groans itself still.",
        lose: "The timber goes in crooked, snaps, and the pieces go round with the wheel.",
      },
      {
        id: "a06-under",
        label: "Go down under the walkway and clear the gate from below",
        ability: "grit",
        tn: 18,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You surface on the far side with a fistful of weed and a broken paddle, and the race running clean.",
        lose: "The current puts you along the stones and the wheel goes over you once before you find a beam.",
      },
    ],
  },
  {
    id: "a07",
    title: "Kessit's Wake",
    setup:
      "Old Kessit is laid out on the long table and the wake has been going since noon. His brother has just accused the room of taking the ring off the body, and nobody is leaving until it turns up.",
    tags: ["drink", "corpse"] satisfies Tag[],
    approaches: [
      {
        id: "a07-search",
        label: "Take the room and run the search yourself",
        ability: "charm",
        tn: 16,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You have forty mourners turning out their own pockets and thanking you for the chance.",
        lose: "The room decides a man that keen to search is a man worth searching.",
      },
      {
        id: "a07-hands",
        label: "Look at the hands, not at the mourners",
        ability: "wits",
        tn: 10,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "The ring is where a swollen knuckle put it, under the cuff, and you say so quietly to the brother.",
        lose: "You spend a long minute studying a dead man's hands while the whole wake watches you do it.",
      },
      {
        id: "a07-name",
        label: "Stand on the table and name the thief",
        ability: "nerve",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "You are right, and the room goes very quiet, and then it goes for him instead of you.",
        lose: "You are wrong, and there is nowhere to get down to.",
      },
    ],
  },
  {
    id: "a08",
    title: "The Long Table at Ferrow House",
    setup:
      "You have been seated at the far end of Lady Ferrow's table to be refused politely, and the refusal is coming with the fish. What you need is her name on a writ of passage before the plates are cleared.",
    tags: ["gentry", "oath"] satisfies Tag[],
    approaches: [
      {
        id: "a08-steward",
        label: "Flatter the steward into speaking for you",
        ability: "charm",
        tn: 11,
        deed: 3,
        cost: { renown: 1, dread: 0 },
        reckless: false,
        win: "The steward says one word at her shoulder and she signs it without looking up from her plate.",
        lose: "The steward hears exactly what you are doing and has you seated further down for the next course.",
      },
      {
        id: "a08-charter",
        label: "Quote her father's charter back at her",
        ability: "wits",
        tn: 13,
        deed: 4,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "She checks the clause, finds you right, and signs, because being seen to be wrong costs her more.",
        lose: "You misremember one clause of it, and she walks the whole table through your error.",
      },
      {
        id: "a08-oath",
        label: "Swear the oath she has been waiting for somebody to swear",
        ability: "grit",
        tn: 17,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You say the words in front of her household and she signs, and you will be paying for those words for years.",
        lose: "You say the words, she lets them sit in the air unanswered, and the plates are cleared.",
      },
    ],
  },
  {
    id: "a09",
    title: "Rats in the Grain Loft",
    setup:
      "The loft is alive with rats and the grain under them is the village's seed corn for spring. Somebody has left a lit lamp up there on the boards.",
    tags: ["vermin", "fire"] satisfies Tag[],
    approaches: [
      {
        id: "a09-lamp",
        label: "Get the lamp before anything else",
        ability: "deft",
        tn: 11,
        deed: 3,
        cost: { renown: 1, dread: 0 },
        reckless: false,
        win: "You have the lamp shuttered and down the ladder before the spilled oil can find the chaff.",
        lose: "A rotten board takes your foot, the lamp goes over, and the chaff catches with a sound like a breath.",
      },
      {
        id: "a09-shovel",
        label: "Work the loft over with a shovel and keep working",
        ability: "grit",
        tn: 13,
        deed: 4,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "It takes an hour and you come down grey to the elbows, and the corn is still worth sowing.",
        lose: "They come over your boots in one wave and you are down the ladder before you have decided to be.",
      },
      {
        id: "a09-burn",
        label: "Burn the nest out of the eaves and hold the fire there",
        ability: "wits",
        tn: 17,
        deed: 8,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "The eaves go up, the rats go out into the yard, and the fire stops exactly where you said it would.",
        lose: "The fire does not stop where you said it would, and the seed corn goes up with the roof.",
      },
    ],
  },
  {
    id: "a10",
    title: "The Bell in the Burnt Chapel",
    setup:
      "The chapel roof burned out last week and the bell is still up in the tower on a frame nobody trusts. The parish will pay to have it down whole, and the priest is watching from the churchyard wall.",
    tags: ["clergy", "height"] satisfies Tag[],
    approaches: [
      {
        id: "a10-sling",
        label: "Climb the frame and sling it properly",
        ability: "deft",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "The bell comes down turning slowly in the sling and touches the ground as though it had been set there.",
        lose: "A charred crossmember lets go under your weight and you come down the inside of the tower with it.",
      },
      {
        id: "a10-scaffold",
        label: "Talk the parish into paying for scaffolding first",
        ability: "charm",
        tn: 16,
        deed: 7,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "The priest finds the money by the afternoon, and the job becomes safe and dull and yours.",
        lose: "The priest hears an excuse rather than a plan, and offers the work to somebody else.",
      },
      {
        id: "a10-drop",
        label: "Cut the frame and drop it",
        ability: "brawn",
        tn: 9,
        deed: 2,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "It goes through the vestry floor and rings once, whole, and every soul in the churchyard is looking at you.",
        lose: "It cracks on the flagstones, and the note it makes is the sound of money leaving.",
      },
    ],
  },
  {
    id: "a11",
    title: "Market Day, Two Hours Late",
    setup:
      "Your stall pitch has been sold twice and the market is already full, and the man standing on your ground has a receipt as well. The bell that closes trading is two hours off.",
    tags: ["crowd", "trade"] satisfies Tag[],
    approaches: [
      {
        id: "a11-clerk",
        label: "Argue it out in front of the clerk",
        ability: "charm",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "The clerk rules for you because you were the one who stayed polite, and the whole row hears him do it.",
        lose: "The clerk rules against you, and now the row knows your name and how you took it.",
      },
      {
        id: "a11-receipt",
        label: "Find the error on the other receipt",
        ability: "wits",
        tn: 10,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "His paper is for the Tuesday market, and you point at the date gently enough that he cannot make a fight of it.",
        lose: "The error is on your own paper, and he reads it out for you.",
      },
      {
        id: "a11-aisle",
        label: "Set up in the aisle and sell faster than anyone can stop you",
        ability: "deft",
        tn: 16,
        deed: 7,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You are cleared out by the bell with your hands full of coin and half the row furious with you.",
        lose: "The wardens take your trestles, your stock and your pitch for the season.",
      },
    ],
  },
  {
    id: "a12",
    title: "The Ledger at the Sign of the Hook",
    setup:
      "The book that says what you owe is in the back room of the Hook, and the man who keeps it is downstairs being loud about it. There is one other person in the yard tonight who wants that book gone.",
    tags: ["debt", "thief", "lock"] satisfies Tag[],
    approaches: [
      {
        id: "a12-page",
        label: "Get in, find the page, take the page",
        ability: "deft",
        tn: 13,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "One page out at the gutter, folded twice, and the book back on its shelf square to the edge.",
        lose: "You lift the wrong quarter's page, and the right one is now in a hand that knows where to look.",
      },
      {
        id: "a12-yard",
        label: "Work out what the one in the yard wants",
        ability: "wits",
        tn: 11,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "They want the keeper ruined rather than the book burned, and that is a thing you can both have.",
        lose: "You read them wrong, and they leave the yard knowing what you came for.",
      },
      {
        id: "a12-room",
        label: "Settle it with the keeper in front of the room",
        ability: "charm",
        tn: 17,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "He tears the page out himself, in front of drinkers who will all remember that he did.",
        lose: "He counts the room, decides he likes the odds, and the whole bar hears the figure you owe.",
      },
    ],
  },
  {
    id: "a13",
    title: "The Watch on Cinder Lane",
    setup:
      "Two of the night watch have Cinder Lane shut at both ends and you are between them with something under your coat you cannot explain. Their lanterns are working down the walls towards each other.",
    tags: ["patrol", "dark"] satisfies Tag[],
    approaches: [
      {
        id: "a13-story",
        label: "Give them a story with a name in it",
        ability: "charm",
        tn: 17,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "You give them a name they know, and they hold the lantern down while you pass.",
        lose: "They ask for the name a second time, and you give a different one.",
      },
      {
        id: "a13-chute",
        label: "Go up the coal chute and over the wall",
        ability: "deft",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 1 },
        reckless: false,
        win: "You come out in the next yard filthy, unlit and entirely alone.",
        lose: "The chute is narrower than the coal made it look, and you are still in it when the lantern arrives.",
      },
      {
        id: "a13-middle",
        label: "Walk straight down the middle of the lane",
        ability: "nerve",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "You go between them at a working man's pace and neither of them thinks to put out a hand.",
        lose: "One of them puts a hand flat on your chest, and the coat comes open.",
      },
    ],
  },
  {
    id: "a14",
    title: "Something Counting in the Stairwell",
    setup:
      "In the stair of the old assize house somebody is counting slowly upwards, and there is nobody on the stair. It has reached the low forties, and each number is closer than the last.",
    tags: ["uncanny", "ruins"] satisfies Tag[],
    approaches: [
      {
        id: "a14-still",
        label: "Stand still and let it get to the top",
        ability: "nerve",
        tn: 14,
        deed: 5,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "It goes past you, still counting, and the cold goes with it, and the stair is only a stair again.",
        lose: "It stops beside you, waits, and then starts again from one.",
      },
      {
        id: "a14-what",
        label: "Work out what it is counting",
        ability: "wits",
        tn: 12,
        deed: 4,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "Steps. There are ninety one and it is naming them, and once you know that you can walk up past it.",
        lose: "You are still working on it when it reaches the number you are standing on.",
      },
      {
        id: "a14-answer",
        label: "Answer it, and count louder",
        ability: "charm",
        tn: 18,
        deed: 9,
        cost: { renown: 4, dread: 2 },
        reckless: true,
        win: "You take the count off it at sixty and carry it to the top yourself, and the house lets you finish.",
        lose: "Something in that stair learns your voice, and afterwards you can hear it using it.",
      },
    ],
  },
  {
    id: "a15",
    title: "The Lock on the Coldroom Door",
    setup:
      "The butcher's coldroom is locked from the inside and the man with the only key has been in there since yesterday. The frost standing on the handle says how cold it is behind the door.",
    tags: ["lock", "cold", "corpse", "vermin"] satisfies Tag[],
    approaches: [
      {
        id: "a15-pick",
        label: "Pick it",
        ability: "deft",
        tn: 12,
        deed: 4,
        cost: { renown: 2, dread: 0 },
        reckless: false,
        win: "The wards are stiff with frost but they turn, and the door opens on a room with all its air still in it.",
        lose: "The pick snaps in the cold, and the broken end is now in the lock with him.",
      },
      {
        id: "a15-hinges",
        label: "Take the hinges off instead",
        ability: "wits",
        tn: 10,
        deed: 3,
        cost: { renown: 1, dread: 1 },
        reckless: false,
        win: "Two pins out and the door leans into your hands, and you never touched the lock at all.",
        lose: "The pins are peened over, and all you have done is turn a good knife into scrap.",
      },
      {
        id: "a15-shoulder",
        label: "Put your shoulder through the door",
        ability: "brawn",
        tn: 16,
        deed: 8,
        cost: { renown: 3, dread: 2 },
        reckless: true,
        win: "The frame gives at the third go and you have him out on the sawdust with his coat open and his colour coming back.",
        lose: "The door holds twice, and the third time something in your shoulder goes instead.",
      },
    ],
  },
];
